### ISSUE TITLE
Add  delay on failed nfc authentication

### ISSUE THREAD

**Issue by riedel** [l-nn-rt/nfc-door-control-system#1]
To avoid brute forcing the nfc id space, there should be a delay if an id is not matched against the local database

**Comment by l-nn-rt** [comment]
Isn't that issue for the [esp32-firmware](https://github.com/davidgru/nfc-door-control-system-esp32-firmware)

**Comment by l-nn-rt** [comment]
Implemented it at [esp32-firmware](https://github.com/davidgru/nfc-door-control-system-esp32-firmware)
